import "./horas.js";
import "./ponentes.js";
import "./admin.js";
import "./formulario.js";
import "./navegacion.js";
import "./tags.js";
import "./slider.js";
import "./tilt.js"; 
import "./snik.js";
import "./mapa.js";
import "./registro.js"
import "./regalos.js"